// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBihcut9B12mf6GTRp4WafiH-nD3pDS13U',
    appId: '1:747578993727:web:d522053bdc015fc6031c8a',
    messagingSenderId: '747578993727',
    projectId: 'fir-2-6e5e8',
    authDomain: 'fir-2-6e5e8.firebaseapp.com',
    storageBucket: 'fir-2-6e5e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI69c0J00SvzA-d9avz012jEi55XYKi6o',
    appId: '1:747578993727:android:7d9dcf2af907e774031c8a',
    messagingSenderId: '747578993727',
    projectId: 'fir-2-6e5e8',
    storageBucket: 'fir-2-6e5e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCswrnaGcxaYGHVqOrBV3ByB8l8RhSAVj0',
    appId: '1:747578993727:ios:596133c7a65b477d031c8a',
    messagingSenderId: '747578993727',
    projectId: 'fir-2-6e5e8',
    storageBucket: 'fir-2-6e5e8.firebasestorage.app',
    iosBundleId: 'com.example.latestFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCswrnaGcxaYGHVqOrBV3ByB8l8RhSAVj0',
    appId: '1:747578993727:ios:596133c7a65b477d031c8a',
    messagingSenderId: '747578993727',
    projectId: 'fir-2-6e5e8',
    storageBucket: 'fir-2-6e5e8.firebasestorage.app',
    iosBundleId: 'com.example.latestFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBihcut9B12mf6GTRp4WafiH-nD3pDS13U',
    appId: '1:747578993727:web:f7a505d93056a11c031c8a',
    messagingSenderId: '747578993727',
    projectId: 'fir-2-6e5e8',
    authDomain: 'fir-2-6e5e8.firebaseapp.com',
    storageBucket: 'fir-2-6e5e8.firebasestorage.app',
  );
}
